-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-09-04 05:22:47 BRT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ACAO_MANUTENCAO 
    ( 
     cd_acao          NUMBER  NOT NULL , 
     cd_os            NUMBER  NOT NULL , 
     ds_acao          VARCHAR2 (255)  NOT NULL , 
     responsavel_exec VARCHAR2 (100) , 
     ts_inicio        TIMESTAMP  NOT NULL , 
     ts_fim           TIMESTAMP , 
     custo_real       NUMBER 
    ) 
    LOGGING 
;

ALTER TABLE ACAO_MANUTENCAO 
    ADD CONSTRAINT ACAO_MANUTENCAO_PK PRIMARY KEY ( cd_acao ) ;

CREATE TABLE ALERTA 
    ( 
     cd_alerta   NUMBER  NOT NULL , 
     tp_alerta   VARCHAR2 (50)  NOT NULL , 
     ds_alerta   VARCHAR2 (255)  NOT NULL , 
     st_alerta   VARCHAR2 (20)  NOT NULL , 
     prioridade  NUMBER , 
     ts_emissao  TIMESTAMP  NOT NULL , 
     cd_anomalia NUMBER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE ALERTA 
    ADD CONSTRAINT ALERTA_PK PRIMARY KEY ( cd_alerta ) ;

CREATE TABLE ANOMALIA 
    ( 
     cd_anomalia NUMBER  NOT NULL , 
     tp_anomalia VARCHAR2 (50)  NOT NULL , 
     score       NUMBER  NOT NULL , 
     gravidade   VARCHAR2 (20)  NOT NULL , 
     cd_sensor   NUMBER  NOT NULL , 
     ts_inicio   TIMESTAMP  NOT NULL , 
     ts_fim      TIMESTAMP 
    ) 
    LOGGING 
;

ALTER TABLE ANOMALIA 
    ADD CONSTRAINT ANOMALIA_PK PRIMARY KEY ( cd_anomalia ) ;

CREATE TABLE CENARIO_SIMULACAO 
    ( 
     cd_cenario      NUMBER  NOT NULL , 
     cd_modelo       NUMBER  NOT NULL , 
     cd_maquina      NUMBER  NOT NULL , 
     nm_cenario      VARCHAR2 (100)  NOT NULL , 
     parametros_json CLOB  NOT NULL , 
     ts_execucao     TIMESTAMP  NOT NULL , 
     resultado_json  CLOB  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE CENARIO_SIMULACAO 
    ADD CONSTRAINT CENARIO_SIMULACAO_PK PRIMARY KEY ( cd_cenario ) ;

CREATE TABLE CUSTO_EVIDADO 
    ( 
     cd_custo         NUMBER  NOT NULL , 
     cd_alerta        NUMBER , 
     cd_acao          NUMBER , 
     estimativa_valor NUMBER  NOT NULL , 
     metodologia      VARCHAR2 (100)  NOT NULL , 
     moeda            CHAR (3)  NOT NULL , 
     ts_registro      TIMESTAMP  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE CUSTO_EVIDADO 
    ADD CONSTRAINT CUSTO_EVIDADO_PK PRIMARY KEY ( cd_custo ) ;

CREATE TABLE DATASET 
    ( 
     cd_dataset      NUMBER  NOT NULL , 
     nm_dataset      VARCHAR2 (100)  NOT NULL , 
     fonte           VARCHAR2 (100)  NOT NULL , 
     num_registros   NUMBER , 
     caminho_arquivo VARCHAR2 (255)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE DATASET 
    ADD CONSTRAINT DATASET_PK PRIMARY KEY ( cd_dataset ) ;

CREATE TABLE EVENTO_PARADA 
    ( 
     cd_parada   NUMBER  NOT NULL , 
     cd_maquina  NUMBER  NOT NULL , 
     ts_inicio   TIMESTAMP  NOT NULL , 
     ts_fim      TIMESTAMP  NOT NULL , 
     motivo      VARCHAR2 (100) , 
     duracao_min NUMBER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE EVENTO_PARADA 
    ADD CONSTRAINT EVENTO_PARADA_PK PRIMARY KEY ( cd_parada ) ;

CREATE TABLE GAMIFICACAO_EVENTO 
    ( 
     cd_evento_gam NUMBER  NOT NULL , 
     cd_usuario    NUMBER  NOT NULL , 
     tp_evento     VARCHAR2 (50)  NOT NULL , 
     pontos        NUMBER  NOT NULL , 
     ts_evento     TIMESTAMP  NOT NULL , 
     cd_alerta     NUMBER 
    ) 
    LOGGING 
;

ALTER TABLE GAMIFICACAO_EVENTO 
    ADD CONSTRAINT GAMIFICACAO_EVENTO_PK PRIMARY KEY ( cd_evento_gam ) ;

CREATE TABLE GEMEO_DIGITAL_MODELO 
    ( 
     cd_modelo     NUMBER  NOT NULL , 
     versao        VARCHAR2 (20)  NOT NULL , 
     tp_modelo     VARCHAR2 (50)  NOT NULL , 
     ds_hiperparam VARCHAR2 (255) 
    ) 
    LOGGING 
;

ALTER TABLE GEMEO_DIGITAL_MODELO 
    ADD CONSTRAINT GEMEO_DIGITAL_MODELO_PK PRIMARY KEY ( cd_modelo ) ;

CREATE TABLE KPI_OEE 
    ( 
     cd_kpi          NUMBER  NOT NULL , 
     cd_maquina      NUMBER  NOT NULL , 
     dt_ref          DATE  NOT NULL , 
     disponibilidade NUMBER  NOT NULL , 
     performance     NUMBER  NOT NULL , 
     qualidade       NUMBER  NOT NULL , 
     oee             NUMBER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE KPI_OEE 
    ADD CONSTRAINT KPI_OEE_PK PRIMARY KEY ( cd_kpi ) ;

CREATE TABLE LEITURA_SENSOR 
    ( 
     cd_leitura NUMBER  NOT NULL , 
     cd_sensor  NUMBER  NOT NULL , 
     ts_leitura TIMESTAMP  NOT NULL , 
     vl_medido  NUMBER  NOT NULL , 
     cd_msg     NUMBER 
    ) 
    LOGGING 
;

ALTER TABLE LEITURA_SENSOR 
    ADD CONSTRAINT LEITURA_SENSOR_PK PRIMARY KEY ( cd_leitura ) ;

CREATE TABLE LINHA_PRODUCAO 
    ( 
     cd_linha NUMBER  NOT NULL , 
     nm_linha VARCHAR2 (100)  NOT NULL , 
     cd_site  NUMBER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE LINHA_PRODUCAO 
    ADD CONSTRAINT LINHA_PRODUCAO_PK PRIMARY KEY ( cd_linha ) ;

CREATE TABLE MAQUINA 
    ( 
     cd_maquina    NUMBER  NOT NULL , 
     nm_maquina    VARCHAR2 (100)  NOT NULL , 
     tp_maquina    VARCHAR2 (50)  NOT NULL , 
     nm_fabricante VARCHAR2 (100) , 
     nm_modelo     VARCHAR2 (100) , 
     cd_linha      NUMBER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE MAQUINA 
    ADD CONSTRAINT MAQUINA_PK PRIMARY KEY ( cd_maquina ) ;

CREATE TABLE MENSAGEM_MQTT 
    ( 
     cd_msg       NUMBER  NOT NULL , 
     cd_topico    NUMBER  NOT NULL , 
     ts_evento    TIMESTAMP  NOT NULL , 
     payload_json CLOB  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE MENSAGEM_MQTT 
    ADD CONSTRAINT MENSAGEM_MQTT_PK PRIMARY KEY ( cd_msg ) ;

CREATE TABLE ORDEM_MANUTENCAO 
    ( 
     cd_os         NUMBER  NOT NULL , 
     num_os_ext    VARCHAR2 (50) , 
     tp_os         VARCHAR2 (50)  NOT NULL , 
     st_os         VARCHAR2 (20)  NOT NULL , 
     ts_abertura   TIMESTAMP  NOT NULL , 
     ts_fechamento TIMESTAMP , 
     cd_alerta     NUMBER , 
     cd_maquina    NUMBER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE ORDEM_MANUTENCAO 
    ADD CONSTRAINT ORDEM_MANUTENCAO_PK PRIMARY KEY ( cd_os ) ;

CREATE TABLE POLITICA_RL 
    ( 
     cd_politica      NUMBER  NOT NULL , 
     algoritmo        VARCHAR2 (50)  NOT NULL , 
     versao           VARCHAR2 (20)  NOT NULL , 
     recompensa_media NUMBER , 
     cd_modelo        NUMBER  NOT NULL , 
     st_implantada    CHAR (1) 
    ) 
    LOGGING 
;

ALTER TABLE POLITICA_RL 
    ADD 
    CHECK (st_implantada IN ('N', 'S')) 
;

ALTER TABLE POLITICA_RL 
    ADD CONSTRAINT POLITICA_RL_PK PRIMARY KEY ( cd_politica ) ;

CREATE TABLE SENSOR 
    ( 
     cd_sensor      NUMBER  NOT NULL , 
     tp_sensor      VARCHAR2 (50)  NOT NULL , 
     nm_modelo      VARCHAR2 (100) , 
     unidade        VARCHAR2 (20)  NOT NULL , 
     cd_tipo_sensor NUMBER  NOT NULL , 
     cd_maquina     NUMBER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE SENSOR 
    ADD CONSTRAINT SENSOR_PK PRIMARY KEY ( cd_sensor ) ;

CREATE TABLE SITE 
    ( 
     cd_site   NUMBER  NOT NULL , 
     nm_site   VARCHAR2 (100)  NOT NULL , 
     sg_pais   CHAR (2)  NOT NULL , 
     nm_cidade VARCHAR2 (100)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE SITE 
    ADD CONSTRAINT SITE_PK PRIMARY KEY ( cd_site ) ;

CREATE TABLE TIPO_SENSOR 
    ( 
     cd_tipo_sensor NUMBER  NOT NULL , 
     ds_tipo        VARCHAR2 (50)  NOT NULL , 
     unidade        VARCHAR2 (20)  NOT NULL , 
     vl_min         NUMBER , 
     vl_max         NUMBER 
    ) 
    LOGGING 
;

ALTER TABLE TIPO_SENSOR 
    ADD CONSTRAINT TIPO_SENSOR_PK PRIMARY KEY ( cd_tipo_sensor ) ;

CREATE TABLE TOPICO_MQTT 
    ( 
     cd_topico NUMBER  NOT NULL , 
     nm_topico VARCHAR2 (100)  NOT NULL , 
     ds_schema VARCHAR2 (255) 
    ) 
    LOGGING 
;

ALTER TABLE TOPICO_MQTT 
    ADD CONSTRAINT TOPICO_MQTT_PK PRIMARY KEY ( cd_topico ) ;

CREATE TABLE TREINO_MODELO 
    ( 
     cd_treino     NUMBER  NOT NULL , 
     cd_dataset    NUMBER  NOT NULL , 
     tp_problema   VARCHAR2 (50)  NOT NULL , 
     algoritmo     VARCHAR2 (50)  NOT NULL , 
     metricas_json CLOB  NOT NULL , 
     artefato_uri  VARCHAR2 (255)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE TREINO_MODELO 
    ADD CONSTRAINT TREINO_MODELO_PK PRIMARY KEY ( cd_treino ) ;

CREATE TABLE USUARIO 
    ( 
     cd_usuario NUMBER  NOT NULL , 
     nm_usuario VARCHAR2 (100)  NOT NULL , 
     perfil     VARCHAR2 (50)  NOT NULL , 
     email      VARCHAR2 (100)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE USUARIO 
    ADD CONSTRAINT USUARIO_PK PRIMARY KEY ( cd_usuario ) ;

ALTER TABLE ACAO_MANUTENCAO 
    ADD CONSTRAINT fk_acao_os FOREIGN KEY 
    ( 
     cd_os
    ) 
    REFERENCES ORDEM_MANUTENCAO 
    ( 
     cd_os
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ALERTA 
    ADD CONSTRAINT fk_alerta_anomalia FOREIGN KEY 
    ( 
     cd_anomalia
    ) 
    REFERENCES ANOMALIA 
    ( 
     cd_anomalia
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ANOMALIA 
    ADD CONSTRAINT fk_anomalia_sensor FOREIGN KEY 
    ( 
     cd_sensor
    ) 
    REFERENCES SENSOR 
    ( 
     cd_sensor
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE CENARIO_SIMULACAO 
    ADD CONSTRAINT fk_cenario_maquina FOREIGN KEY 
    ( 
     cd_maquina
    ) 
    REFERENCES MAQUINA 
    ( 
     cd_maquina
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE CENARIO_SIMULACAO 
    ADD CONSTRAINT fk_cenario_modelo FOREIGN KEY 
    ( 
     cd_modelo
    ) 
    REFERENCES GEMEO_DIGITAL_MODELO 
    ( 
     cd_modelo
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE CUSTO_EVIDADO 
    ADD CONSTRAINT fk_custo_acao FOREIGN KEY 
    ( 
     cd_acao
    ) 
    REFERENCES ACAO_MANUTENCAO 
    ( 
     cd_acao
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE CUSTO_EVIDADO 
    ADD CONSTRAINT fk_custo_alerta FOREIGN KEY 
    ( 
     cd_alerta
    ) 
    REFERENCES ALERTA 
    ( 
     cd_alerta
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE GAMIFICACAO_EVENTO 
    ADD CONSTRAINT fk_gam_alerta FOREIGN KEY 
    ( 
     cd_alerta
    ) 
    REFERENCES ALERTA 
    ( 
     cd_alerta
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE GAMIFICACAO_EVENTO 
    ADD CONSTRAINT fk_gam_user FOREIGN KEY 
    ( 
     cd_usuario
    ) 
    REFERENCES USUARIO 
    ( 
     cd_usuario
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE KPI_OEE 
    ADD CONSTRAINT fk_kpi_maquina FOREIGN KEY 
    ( 
     cd_maquina
    ) 
    REFERENCES MAQUINA 
    ( 
     cd_maquina
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE LEITURA_SENSOR 
    ADD CONSTRAINT fk_leitura_msg FOREIGN KEY 
    ( 
     cd_msg
    ) 
    REFERENCES MENSAGEM_MQTT 
    ( 
     cd_msg
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE LEITURA_SENSOR 
    ADD CONSTRAINT fk_leitura_sensor FOREIGN KEY 
    ( 
     cd_sensor
    ) 
    REFERENCES SENSOR 
    ( 
     cd_sensor
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE LINHA_PRODUCAO 
    ADD CONSTRAINT fk_linha_site FOREIGN KEY 
    ( 
     cd_site
    ) 
    REFERENCES SITE 
    ( 
     cd_site
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE MAQUINA 
    ADD CONSTRAINT fk_maquina_linha FOREIGN KEY 
    ( 
     cd_linha
    ) 
    REFERENCES LINHA_PRODUCAO 
    ( 
     cd_linha
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE MENSAGEM_MQTT 
    ADD CONSTRAINT fk_msg_topico FOREIGN KEY 
    ( 
     cd_topico
    ) 
    REFERENCES TOPICO_MQTT 
    ( 
     cd_topico
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ORDEM_MANUTENCAO 
    ADD CONSTRAINT fk_os_alerta FOREIGN KEY 
    ( 
     cd_alerta
    ) 
    REFERENCES ALERTA 
    ( 
     cd_alerta
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ORDEM_MANUTENCAO 
    ADD CONSTRAINT fk_os_maquina FOREIGN KEY 
    ( 
     cd_maquina
    ) 
    REFERENCES MAQUINA 
    ( 
     cd_maquina
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE EVENTO_PARADA 
    ADD CONSTRAINT fk_parada_maquina FOREIGN KEY 
    ( 
     cd_maquina
    ) 
    REFERENCES MAQUINA 
    ( 
     cd_maquina
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE POLITICA_RL 
    ADD CONSTRAINT fk_politica_modelo FOREIGN KEY 
    ( 
     cd_modelo
    ) 
    REFERENCES GEMEO_DIGITAL_MODELO 
    ( 
     cd_modelo
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE SENSOR 
    ADD CONSTRAINT fk_sensor_maquina FOREIGN KEY 
    ( 
     cd_maquina
    ) 
    REFERENCES MAQUINA 
    ( 
     cd_maquina
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE SENSOR 
    ADD CONSTRAINT fk_sensor_tipo FOREIGN KEY 
    ( 
     cd_tipo_sensor
    ) 
    REFERENCES TIPO_SENSOR 
    ( 
     cd_tipo_sensor
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE TREINO_MODELO 
    ADD CONSTRAINT fk_treino_dataset FOREIGN KEY 
    ( 
     cd_dataset
    ) 
    REFERENCES DATASET 
    ( 
     cd_dataset
    ) 
    NOT DEFERRABLE 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            22
-- CREATE INDEX                             0
-- ALTER TABLE                             45
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
