-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
-- Script adaptado para PostgreSQL

CREATE TABLE ACAO_MANUTENCAO 
    ( 
     cd_acao          SERIAL  NOT NULL , 
     cd_os            INTEGER  NOT NULL , 
     ds_acao          VARCHAR (255)  NOT NULL , 
     responsavel_exec VARCHAR (100) , 
     ts_inicio        TIMESTAMP  NOT NULL , 
     ts_fim           TIMESTAMP , 
     custo_real       NUMERIC 
    )  
;

ALTER TABLE ACAO_MANUTENCAO 
    ADD CONSTRAINT ACAO_MANUTENCAO_PK PRIMARY KEY ( cd_acao ) ;

CREATE TABLE ALERTA 
    ( 
     cd_alerta   SERIAL  NOT NULL , 
     tp_alerta   VARCHAR (50)  NOT NULL , 
     ds_alerta   VARCHAR (255)  NOT NULL , 
     st_alerta   VARCHAR (20)  NOT NULL , 
     prioridade  INTEGER , 
     ts_emissao  TIMESTAMP  NOT NULL , 
     cd_anomalia INTEGER  NOT NULL 
    )  
;

ALTER TABLE ALERTA 
    ADD CONSTRAINT ALERTA_PK PRIMARY KEY ( cd_alerta ) ;

CREATE TABLE ANOMALIA 
    ( 
     cd_anomalia SERIAL  NOT NULL , 
     tp_anomalia VARCHAR (50)  NOT NULL , 
     score       NUMERIC  NOT NULL , 
     gravidade   VARCHAR (20)  NOT NULL , 
     cd_sensor   INTEGER  NOT NULL , 
     ts_inicio   TIMESTAMP  NOT NULL , 
     ts_fim      TIMESTAMP 
    )  
;

ALTER TABLE ANOMALIA 
    ADD CONSTRAINT ANOMALIA_PK PRIMARY KEY ( cd_anomalia ) ;

CREATE TABLE CENARIO_SIMULACAO 
    ( 
     cd_cenario      SERIAL  NOT NULL , 
     cd_modelo       INTEGER  NOT NULL , 
     cd_maquina      INTEGER  NOT NULL , 
     nm_cenario      VARCHAR (100)  NOT NULL , 
     parametros_json TEXT  NOT NULL , 
     ts_execucao     TIMESTAMP  NOT NULL , 
     resultado_json  TEXT  NOT NULL 
    )  
;

ALTER TABLE CENARIO_SIMULACAO 
    ADD CONSTRAINT CENARIO_SIMULACAO_PK PRIMARY KEY ( cd_cenario ) ;

CREATE TABLE CUSTO_EVIDADO 
    ( 
     cd_custo         SERIAL  NOT NULL , 
     cd_alerta        INTEGER , 
     cd_acao          INTEGER , 
     estimativa_valor NUMERIC  NOT NULL , 
     metodologia      VARCHAR (100)  NOT NULL , 
     moeda            CHAR (3)  NOT NULL , 
     ts_registro      TIMESTAMP  NOT NULL 
    )  
;

ALTER TABLE CUSTO_EVIDADO 
    ADD CONSTRAINT CUSTO_EVIDADO_PK PRIMARY KEY ( cd_custo ) ;

CREATE TABLE DATASET 
    ( 
     cd_dataset      SERIAL  NOT NULL , 
     nm_dataset      VARCHAR (100)  NOT NULL , 
     fonte           VARCHAR (100)  NOT NULL , 
     num_registros   INTEGER , 
     caminho_arquivo VARCHAR (255)  NOT NULL 
    )  
;

ALTER TABLE DATASET 
    ADD CONSTRAINT DATASET_PK PRIMARY KEY ( cd_dataset ) ;

CREATE TABLE EVENTO_PARADA 
    ( 
     cd_parada   SERIAL  NOT NULL , 
     cd_maquina  INTEGER  NOT NULL , 
     ts_inicio   TIMESTAMP  NOT NULL , 
     ts_fim      TIMESTAMP  NOT NULL , 
     motivo      VARCHAR (100) , 
     duracao_min INTEGER  NOT NULL 
    )  
;

ALTER TABLE EVENTO_PARADA 
    ADD CONSTRAINT EVENTO_PARADA_PK PRIMARY KEY ( cd_parada ) ;

CREATE TABLE GAMIFICACAO_EVENTO 
    ( 
     cd_evento_gam SERIAL  NOT NULL , 
     cd_usuario    INTEGER  NOT NULL , 
     tp_evento     VARCHAR (50)  NOT NULL , 
     pontos        INTEGER  NOT NULL , 
     ts_evento     TIMESTAMP  NOT NULL , 
     cd_alerta     INTEGER 
    )  
;

ALTER TABLE GAMIFICACAO_EVENTO 
    ADD CONSTRAINT GAMIFICACAO_EVENTO_PK PRIMARY KEY ( cd_evento_gam ) ;

CREATE TABLE GEMEO_DIGITAL_MODELO 
    ( 
     cd_modelo     SERIAL  NOT NULL , 
     versao        VARCHAR (20)  NOT NULL , 
     tp_modelo     VARCHAR (50)  NOT NULL , 
     ds_hiperparam VARCHAR (255) 
    )  
;

ALTER TABLE GEMEO_DIGITAL_MODELO 
    ADD CONSTRAINT GEMEO_DIGITAL_MODELO_PK PRIMARY KEY ( cd_modelo ) ;

CREATE TABLE KPI_OEE 
    ( 
     cd_kpi          SERIAL  NOT NULL , 
     cd_maquina      INTEGER  NOT NULL , 
     dt_ref          DATE  NOT NULL , 
     disponibilidade NUMERIC  NOT NULL , 
     performance     NUMERIC  NOT NULL , 
     qualidade       NUMERIC  NOT NULL , 
     oee             NUMERIC  NOT NULL 
    )  
;

ALTER TABLE KPI_OEE 
    ADD CONSTRAINT KPI_OEE_PK PRIMARY KEY ( cd_kpi ) ;

CREATE TABLE LEITURA_SENSOR 
    ( 
     cd_leitura SERIAL  NOT NULL , 
     cd_sensor  INTEGER  NOT NULL , 
     ts_leitura TIMESTAMP  NOT NULL , 
     vl_medido  NUMERIC  NOT NULL , 
     cd_msg     INTEGER 
    )  
;

ALTER TABLE LEITURA_SENSOR 
    ADD CONSTRAINT LEITURA_SENSOR_PK PRIMARY KEY ( cd_leitura ) ;

CREATE TABLE LINHA_PRODUCAO 
    ( 
     cd_linha SERIAL  NOT NULL , 
     nm_linha VARCHAR (100)  NOT NULL , 
     cd_site  INTEGER  NOT NULL 
    )  
;

ALTER TABLE LINHA_PRODUCAO 
    ADD CONSTRAINT LINHA_PRODUCAO_PK PRIMARY KEY ( cd_linha ) ;

CREATE TABLE MAQUINA 
    ( 
     cd_maquina    SERIAL  NOT NULL , 
     nm_maquina    VARCHAR (100)  NOT NULL , 
     tp_maquina    VARCHAR (50)  NOT NULL , 
     nm_fabricante VARCHAR (100) , 
     nm_modelo     VARCHAR (100) , 
     cd_linha      INTEGER  NOT NULL 
    )  
;

ALTER TABLE MAQUINA 
    ADD CONSTRAINT MAQUINA_PK PRIMARY KEY ( cd_maquina ) ;

CREATE TABLE MENSAGEM_MQTT 
    ( 
     cd_msg       SERIAL  NOT NULL , 
     cd_topico    INTEGER  NOT NULL , 
     ts_evento    TIMESTAMP  NOT NULL , 
     payload_json TEXT  NOT NULL 
    )  
;

ALTER TABLE MENSAGEM_MQTT 
    ADD CONSTRAINT MENSAGEM_MQTT_PK PRIMARY KEY ( cd_msg ) ;

CREATE TABLE ORDEM_MANUTENCAO 
    ( 
     cd_os         SERIAL  NOT NULL , 
     num_os_ext    VARCHAR (50) , 
     tp_os         VARCHAR (50)  NOT NULL , 
     st_os         VARCHAR (20)  NOT NULL , 
     ts_abertura   TIMESTAMP  NOT NULL , 
     ts_fechamento TIMESTAMP , 
     cd_alerta     INTEGER , 
     cd_maquina    INTEGER  NOT NULL 
    )  
;

ALTER TABLE ORDEM_MANUTENCAO 
    ADD CONSTRAINT ORDEM_MANUTENCAO_PK PRIMARY KEY ( cd_os ) ;

CREATE TABLE POLITICA_RL 
    ( 
     cd_politica      SERIAL  NOT NULL , 
     algoritmo        VARCHAR (50)  NOT NULL , 
     versao           VARCHAR (20)  NOT NULL , 
     recompensa_media NUMERIC , 
     cd_modelo        INTEGER  NOT NULL , 
     st_implantada    CHAR (1) 
    )  
;

ALTER TABLE POLITICA_RL
    ADD 
    CHECK (st_implantada IN ('N', 'S')) 
;

ALTER TABLE POLITICA_RL 
    ADD CONSTRAINT POLITICA_RL_PK PRIMARY KEY ( cd_politica ) ;

CREATE TABLE SENSOR 
    ( 
     cd_sensor      SERIAL  NOT NULL , 
     tp_sensor      VARCHAR (50)  NOT NULL , 
     nm_modelo      VARCHAR (100) , 
     unidade        VARCHAR (20)  NOT NULL , 
     cd_tipo_sensor INTEGER  NOT NULL , 
     cd_maquina     INTEGER  NOT NULL 
    )  
;

ALTER TABLE SENSOR 
    ADD CONSTRAINT SENSOR_PK PRIMARY KEY ( cd_sensor ) ;

CREATE TABLE SITE 
    ( 
     cd_site   SERIAL  NOT NULL , 
     nm_site   VARCHAR (100)  NOT NULL , 
     sg_pais   CHAR (2)  NOT NULL , 
     nm_cidade VARCHAR (100)  NOT NULL 
    )  
;

ALTER TABLE SITE 
    ADD CONSTRAINT SITE_PK PRIMARY KEY ( cd_site ) ;

CREATE TABLE TIPO_SENSOR 
    ( 
     cd_tipo_sensor SERIAL  NOT NULL , 
     ds_tipo        VARCHAR (50)  NOT NULL , 
     unidade        VARCHAR (20)  NOT NULL , 
     vl_min         NUMERIC , 
     vl_max         NUMERIC 
    )  
;

ALTER TABLE TIPO_SENSOR 
    ADD CONSTRAINT TIPO_SENSOR_PK PRIMARY KEY ( cd_tipo_sensor ) ;

CREATE TABLE TOPICO_MQTT 
    ( 
     cd_topico SERIAL  NOT NULL , 
     nm_topico VARCHAR (100)  NOT NULL , 
     ds_schema VARCHAR (255) 
    )  
;

ALTER TABLE TOPICO_MQTT 
    ADD CONSTRAINT TOPICO_MQTT_PK PRIMARY KEY ( cd_topico ) ;

CREATE TABLE TREINO_MODELO 
    ( 
     cd_treino     SERIAL  NOT NULL , 
     cd_dataset    INTEGER  NOT NULL , 
     tp_problema   VARCHAR (50)  NOT NULL , 
     algoritmo     VARCHAR (50)  NOT NULL , 
     metricas_json TEXT  NOT NULL , 
     artefato_uri  VARCHAR (255)  NOT NULL 
    )  
;

ALTER TABLE TREINO_MODELO 
    ADD CONSTRAINT TREINO_MODELO_PK PRIMARY KEY ( cd_treino ) ;

CREATE TABLE USUARIO 
    ( 
     cd_usuario SERIAL  NOT NULL , 
     nm_usuario VARCHAR (100)  NOT NULL , 
     perfil     VARCHAR (50)  NOT NULL , 
     email      VARCHAR (100)  NOT NULL 
    )  
;

ALTER TABLE USUARIO 
    ADD CONSTRAINT USUARIO_PK PRIMARY KEY ( cd_usuario ) ;

ALTER TABLE ACAO_MANUTENCAO 
    ADD CONSTRAINT fk_acao_os FOREIGN KEY 
    ( 
     cd_os
    ) 
    REFERENCES ORDEM_MANUTENCAO 
    ( 
     cd_os
    )  
;

ALTER TABLE ALERTA 
    ADD CONSTRAINT fk_alerta_anomalia FOREIGN KEY 
    ( 
     cd_anomalia
    ) 
    REFERENCES ANOMALIA 
    ( 
     cd_anomalia
    )  
;

ALTER TABLE ANOMALIA 
    ADD CONSTRAINT fk_anomalia_sensor FOREIGN KEY 
    ( 
     cd_sensor
    ) 
    REFERENCES SENSOR 
    ( 
     cd_sensor
    )  
;

ALTER TABLE CENARIO_SIMULACAO 
    ADD CONSTRAINT fk_cenario_maquina FOREIGN KEY 
    ( 
     cd_maquina
    ) 
    REFERENCES MAQUINA 
    ( 
     cd_maquina
    )  
;

ALTER TABLE CENARIO_SIMULACAO 
    ADD CONSTRAINT fk_cenario_modelo FOREIGN KEY 
    ( 
     cd_modelo
    ) 
    REFERENCES GEMEO_DIGITAL_MODELO 
    ( 
     cd_modelo
    )  
;

ALTER TABLE CUSTO_EVIDADO 
    ADD CONSTRAINT fk_custo_acao FOREIGN KEY 
    ( 
     cd_acao
    ) 
    REFERENCES ACAO_MANUTENCAO 
    ( 
     cd_acao
    )  
;

ALTER TABLE CUSTO_EVIDADO 
    ADD CONSTRAINT fk_custo_alerta FOREIGN KEY 
    ( 
     cd_alerta
    ) 
    REFERENCES ALERTA 
    ( 
     cd_alerta
    )  
;

ALTER TABLE GAMIFICACAO_EVENTO 
    ADD CONSTRAINT fk_gam_alerta FOREIGN KEY 
    ( 
     cd_alerta
    ) 
    REFERENCES ALERTA 
    ( 
     cd_alerta
    )  
;

ALTER TABLE GAMIFICACAO_EVENTO 
    ADD CONSTRAINT fk_gam_user FOREIGN KEY 
    ( 
     cd_usuario
    ) 
    REFERENCES USUARIO 
    ( 
     cd_usuario
    )  
;

ALTER TABLE KPI_OEE 
    ADD CONSTRAINT fk_kpi_maquina FOREIGN KEY 
    ( 
     cd_maquina
    ) 
    REFERENCES MAQUINA 
    ( 
     cd_maquina
    )  
;

ALTER TABLE LEITURA_SENSOR 
    ADD CONSTRAINT fk_leitura_msg FOREIGN KEY 
    ( 
     cd_msg
    ) 
    REFERENCES MENSAGEM_MQTT 
    ( 
     cd_msg
    )  
;

ALTER TABLE LEITURA_SENSOR 
    ADD CONSTRAINT fk_leitura_sensor FOREIGN KEY 
    ( 
     cd_sensor
    ) 
    REFERENCES SENSOR 
    ( 
     cd_sensor
    )  
;

ALTER TABLE LINHA_PRODUCAO 
    ADD CONSTRAINT fk_linha_site FOREIGN KEY 
    ( 
     cd_site
    ) 
    REFERENCES SITE 
    ( 
     cd_site
    )  
;

ALTER TABLE MAQUINA 
    ADD CONSTRAINT fk_maquina_linha FOREIGN KEY 
    ( 
     cd_linha
    ) 
    REFERENCES LINHA_PRODUCAO 
    ( 
     cd_linha
    )  
;

ALTER TABLE MENSAGEM_MQTT 
    ADD CONSTRAINT fk_msg_topico FOREIGN KEY 
    ( 
     cd_topico
    ) 
    REFERENCES TOPICO_MQTT 
    ( 
     cd_topico
    )  
;

ALTER TABLE ORDEM_MANUTENCAO 
    ADD CONSTRAINT fk_os_alerta FOREIGN KEY 
    ( 
     cd_alerta
    ) 
    REFERENCES ALERTA 
    ( 
     cd_alerta
    )  
;

ALTER TABLE ORDEM_MANUTENCAO 
    ADD CONSTRAINT fk_os_maquina FOREIGN KEY 
    ( 
     cd_maquina
    ) 
    REFERENCES MAQUINA 
    ( 
     cd_maquina
    )  
;

ALTER TABLE EVENTO_PARADA 
    ADD CONSTRAINT fk_parada_maquina FOREIGN KEY 
    ( 
     cd_maquina
    ) 
    REFERENCES MAQUINA 
    ( 
     cd_maquina
    )  
;

ALTER TABLE POLITICA_RL 
    ADD CONSTRAINT fk_politica_modelo FOREIGN KEY 
    ( 
     cd_modelo
    ) 
    REFERENCES GEMEO_DIGITAL_MODELO 
    ( 
     cd_modelo
    )  
;

ALTER TABLE SENSOR 
    ADD CONSTRAINT fk_sensor_maquina FOREIGN KEY 
    ( 
     cd_maquina
    ) 
    REFERENCES MAQUINA 
    ( 
     cd_maquina
    )  
;

ALTER TABLE SENSOR 
    ADD CONSTRAINT fk_sensor_tipo FOREIGN KEY 
    ( 
     cd_tipo_sensor
    ) 
    REFERENCES TIPO_SENSOR 
    ( 
     cd_tipo_sensor
    )  
;

ALTER TABLE TREINO_MODELO 
    ADD CONSTRAINT fk_treino_dataset FOREIGN KEY 
    ( 
     cd_dataset
    ) 
    REFERENCES DATASET 
    ( 
     cd_dataset
    )  
;
